// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse the JSON, add this file to your project and do:
//
//   let welcome = try? JSONDecoder().decode(Welcome.self, from: jsonData)

import Foundation

// MARK: - WelcomeElement
struct Location: Codable, Identifiable {
    let id, starbucksID, name: String
    let brandName: BrandName
    let storeNumber, phoneNumber: String
    let ownershipType: OwnershipType
    let street1, street2, street3, city: String
    let countrySubdivisionCode: String
    let countryCode: CountryCode
    let postalCode, longitude, latitude, timezoneOffset: String
    let timezoneID: TimezoneID
    let timezoneOlsonID: TimezoneOlsonID
    let firstSeen: String
    let lastSeen: LastSeen

    enum CodingKeys: String, CodingKey {
        case id = "Id"
        case starbucksID = "StarbucksId"
        case name = "Name"
        case brandName = "BrandName"
        case storeNumber = "StoreNumber"
        case phoneNumber = "PhoneNumber"
        case ownershipType = "OwnershipType"
        case street1 = "Street1"
        case street2 = "Street2"
        case street3 = "Street3"
        case city = "City"
        case countrySubdivisionCode = "CountrySubdivisionCode"
        case countryCode = "CountryCode"
        case postalCode = "PostalCode"
        case longitude = "Longitude"
        case latitude = "Latitude"
        case timezoneOffset = "TimezoneOffset"
        case timezoneID = "TimezoneId"
        case timezoneOlsonID = "TimezoneOlsonId"
        case firstSeen = "FirstSeen"
        case lastSeen = "LastSeen"
    }
}

enum BrandName: String, Codable {
    case coffeeHouseHoldings = "Coffee House Holdings"
    case evolutionFresh = "Evolution Fresh"
    case starbucks = "Starbucks"
    case teavana = "Teavana"
}

enum CountryCode: String, Codable {
    case ad = "AD"
    case ae = "AE"
    case ar = "AR"
    case at = "AT"
    case au = "AU"
    case aw = "AW"
    case az = "AZ"
    case be = "BE"
    case bg = "BG"
    case bh = "BH"
    case bn = "BN"
    case bo = "BO"
    case br = "BR"
    case bs = "BS"
    case ca = "CA"
    case ch = "CH"
    case cl = "CL"
    case cn = "CN"
    case co = "CO"
    case countryCodeIN = "IN"
    case cr = "CR"
    case cw = "CW"
    case cy = "CY"
    case cz = "CZ"
    case de = "DE"
    case dk = "DK"
    case eg = "EG"
    case es = "ES"
    case fi = "FI"
    case fr = "FR"
    case gb = "GB"
    case gr = "GR"
    case gt = "GT"
    case hu = "HU"
    case id = "ID"
    case ie = "IE"
    case jo = "JO"
    case jp = "JP"
    case kh = "KH"
    case kr = "KR"
    case kw = "KW"
    case kz = "KZ"
    case lb = "LB"
    case lu = "LU"
    case ma = "MA"
    case mc = "MC"
    case mx = "MX"
    case my = "MY"
    case nl = "NL"
    case no = "NO"
    case nz = "NZ"
    case om = "OM"
    case pa = "PA"
    case pe = "PE"
    case ph = "PH"
    case pl = "PL"
    case pr = "PR"
    case pt = "PT"
    case qa = "QA"
    case ro = "RO"
    case ru = "RU"
    case sa = "SA"
    case se = "SE"
    case sg = "SG"
    case sk = "SK"
    case sv = "SV"
    case th = "TH"
    case tr = "TR"
    case tt = "TT"
    case tw = "TW"
    case us = "US"
    case vn = "VN"
    case za = "ZA"
}

enum LastSeen: String, Codable {
    case the232017120000Am = "2/3/2017 12:00:00 AM"
}

enum OwnershipType: String, Codable {
    case co = "CO"
    case fr = "FR"
    case jv = "JV"
    case ls = "LS"
}

enum TimezoneID: String, Codable {
    case alaskanStandardTime = "Alaskan Standard Time"
    case arabStandardTime = "Arab Standard Time"
    case arabianStandardTime = "Arabian Standard Time"
    case argentinaStandardTime = "Argentina Standard Time"
    case atlanticStandardTime = "Atlantic Standard Time"
    case ausEasternStandardTime = "AUS Eastern Standard Time"
    case azerbaijanStandardTime = "Azerbaijan Standard Time"
    case canadaCentralStandardTime = "Canada Central Standard Time"
    case capeVerdeStandardTime = "Cape Verde Standard Time"
    case centralAmericaStandardTime = "Central America Standard Time"
    case centralAsiaStandardTime = "Central Asia Standard Time"
    case centralEuropeStandardTime = "Central Europe Standard Time"
    case centralEuropeanStandardTime = "Central European Standard Time"
    case centralStandardTime = "Central Standard Time"
    case centralStandardTimeMexico = "Central Standard Time (Mexico)"
    case chinaStandardTime = "China Standard Time"
    case eAustraliaStandardTime = "E. Australia Standard Time"
    case eEuropeStandardTime = "E. Europe Standard Time"
    case eSouthAmericaStandardTime = "E. South America Standard Time"
    case easternStandardTime = "Eastern Standard Time"
    case egyptStandardTime = "Egypt Standard Time"
    case ekaterinburgStandardTime = "Ekaterinburg Standard Time"
    case fleStandardTime = "FLE Standard Time"
    case gmtStandardTime = "GMT Standard Time"
    case gtbStandardTime = "GTB Standard Time"
    case hawaiianStandardTime = "Hawaiian Standard Time"
    case indiaStandardTime = "India Standard Time"
    case israelStandardTime = "Israel Standard Time"
    case jordanStandardTime = "Jordan Standard Time"
    case koreaStandardTime = "Korea Standard Time"
    case middleEastStandardTime = "Middle East Standard Time"
    case moroccoStandardTime = "Morocco Standard Time"
    case mountainStandardTime = "Mountain Standard Time"
    case mountainStandardTimeMexico = "Mountain Standard Time (Mexico)"
    case newZealandStandardTime = "New Zealand Standard Time"
    case newfoundlandStandardTime = "Newfoundland Standard Time"
    case pacificSAStandardTime = "Pacific SA Standard Time"
    case pacificStandardTime = "Pacific Standard Time"
    case pakistanStandardTime = "Pakistan Standard Time"
    case romanceStandardTime = "Romance Standard Time"
    case russianStandardTime = "Russian Standard Time"
    case saEasternStandardTime = "SA Eastern Standard Time"
    case saPacificStandardTime = "SA Pacific Standard Time"
    case saWesternStandardTime = "SA Western Standard Time"
    case seAsiaStandardTime = "SE Asia Standard Time"
    case singaporeStandardTime = "Singapore Standard Time"
    case southAfricaStandardTime = "South Africa Standard Time"
    case syriaStandardTime = "Syria Standard Time"
    case taipeiStandardTime = "Taipei Standard Time"
    case tokyoStandardTime = "Tokyo Standard Time"
    case turkeyStandardTime = "Turkey Standard Time"
    case usEasternStandardTime = "US Eastern Standard Time"
    case usMountainStandardTime = "US Mountain Standard Time"
    case utc = "UTC"
    case utc02 = "UTC-02"
    case wCentralAfricaStandardTime = "W. Central Africa Standard Time"
    case wEuropeStandardTime = "W. Europe Standard Time"
    case westAsiaStandardTime = "West Asia Standard Time"
}

enum TimezoneOlsonID: String, Codable {
    case gmt000000AfricaCasablanca = "GMT+000000 Africa/Casablanca"
    case gmt000000AfricaJohannesburg = "GMT+000000 Africa/Johannesburg"
    case gmt000000AmericaBogota = "GMT+000000 America/Bogota"
    case gmt000000AmericaCostaRica = "GMT+000000 America/Costa_Rica"
    case gmt000000AmericaDawsonCree = "GMT+000000 America/Dawson_Cree"
    case gmt000000AmericaElSalvador = "GMT+000000 America/El_Salvador"
    case gmt000000AmericaLaPaz = "GMT+000000 America/La_Paz"
    case gmt000000AmericaPanama = "GMT+000000 America/Panama"
    case gmt000000AmericaPhoenix = "GMT+000000 America/Phoenix"
    case gmt000000AmericaPortOfSPA = "GMT+000000 America/Port_of_Spa"
    case gmt000000AmericaTegucigalpa = "GMT+000000 America/Tegucigalpa"
    case gmt000000AsiaAlmaty = "GMT+000000 Asia/Almaty"
    case gmt000000AsiaBahrain = "GMT+000000 Asia/Bahrain"
    case gmt000000AsiaKuching = "GMT+000000 Asia/Kuching"
    case gmt000000AsiaKuwait = "GMT+000000 Asia/Kuwait"
    case gmt000000AsiaMakassar = "GMT+000000 Asia/Makassar"
    case gmt000000AsiaPhnomPenh = "GMT+000000 Asia/Phnom_Penh"
    case gmt000000AsiaSaigon = "GMT+000000 Asia/Saigon"
    case gmt000000EtcGMT2 = "GMT+000000 Etc/GMT+2"
    case gmt000AtlanticCanary = "GMT+0:00 Atlantic/Canary"
    case gmt000EuropeDublin = "GMT+0:00 Europe/Dublin"
    case gmt000EuropeLisbon = "GMT+0:00 Europe/Lisbon"
    case gmt000EuropeLondon = "GMT+0:00 Europe/London"
    case gmt0300AmericaArgentinaBu = "GMT-03:00 America/Argentina/Bu"
    case gmt0300AmericaSaoPaulo = "GMT-03:00 America/Sao_Paulo"
    case gmt0300AsiaQatar = "GMT+03:00 Asia/Qatar"
    case gmt0300AsiaRiyadh = "GMT+03:00 Asia/Riyadh"
    case gmt0330AmericaStJohns = "GMT-03:30 America/St_Johns"
    case gmt0400AmericaHalifax = "GMT-04:00 America/Halifax"
    case gmt0400AmericaMoncton = "GMT-04:00 America/Moncton"
    case gmt0400AmericaOranjestad = "GMT-04:00 America/Oranjestad"
    case gmt0400AmericaPuertoRico = "GMT-04:00 America/Puerto_Rico"
    case gmt0400AmericaSantiago = "GMT-04:00 America/Santiago"
    case gmt0400AmericaWillemstad = "GMT-04:00 America/Willemstad"
    case gmt0400AsiaDubai = "GMT+04:00 Asia/Dubai"
    case gmt0400AsiaMuscat = "GMT+04:00 Asia/Muscat"
    case gmt0500AmericaIndianapolis = "GMT-05:00 America/Indianapolis"
    case gmt0500AmericaLima = "GMT-05:00 America/Lima"
    case gmt0500AmericaMontreal = "GMT-05:00 America/Montreal"
    case gmt0500AmericaNassau = "GMT-05:00 America/Nassau"
    case gmt0500AmericaNewYork = "GMT-05:00 America/New_York"
    case gmt0500AmericaToronto = "GMT-05:00 America/Toronto"
    case gmt0530AsiaNewDelhi = "GMT+05:30 Asia/New_Delhi"
    case gmt0600AmericaChicago = "GMT-06:00 America/Chicago"
    case gmt0600AmericaMexicoCity = "GMT-06:00 America/Mexico_City"
    case gmt0600AmericaRainyRiver = "GMT-06:00 America/Rainy_River"
    case gmt0600AmericaRegina = "GMT-06:00 America/Regina"
    case gmt0600AmericaWinnipeg = "GMT-06:00 America/Winnipeg"
    case gmt0700AmericaChihuahua = "GMT-07:00 America/Chihuahua"
    case gmt0700AmericaDenver = "GMT-07:00 America/Denver"
    case gmt0700AmericaEdmonton = "GMT-07:00 America/Edmonton"
    case gmt0700AmericaHermosillo = "GMT-07:00 America/Hermosillo"
    case gmt0700AsiaBangkok = "GMT+07:00 Asia/Bangkok"
    case gmt0700AsiaJakarta = "GMT+07:00 Asia/Jakarta"
    case gmt0800AmericaLosAngeles = "GMT-08:00 America/Los_Angeles"
    case gmt0800AmericaTijuana = "GMT-08:00 America/Tijuana"
    case gmt0800AmericaVancouver = "GMT-08:00 America/Vancouver"
    case gmt0800AsiaBeijing = "GMT+08:00 Asia/Beijing"
    case gmt0800AsiaKualaLumpur = "GMT+08:00 Asia/Kuala_Lumpur"
    case gmt0800AsiaMacau = "GMT+08:00 Asia/Macau"
    case gmt0800AsiaManila = "GMT+08:00 Asia/Manila"
    case gmt0800AsiaTaipei = "GMT+08:00 Asia/Taipei"
    case gmt0900AmericaAnchorage = "GMT-09:00 America/Anchorage"
    case gmt0900AsiaSeoul = "GMT+09:00 Asia/Seoul"
    case gmt0900AsiaTokyo = "GMT+09:00 Asia/Tokyo"
    case gmt1000AustraliaBrisbane = "GMT+10:00 Australia/Brisbane"
    case gmt1000AustraliaMelbourne = "GMT+10:00 Australia/Melbourne"
    case gmt1000AustraliaSydney = "GMT+10:00 Australia/Sydney"
    case gmt1000PacificHonolulu = "GMT-10:00 Pacific/Honolulu"
    case gmt100EuropeAmsterdam = "GMT+1:00 Europe/Amsterdam"
    case gmt100EuropeAndorra = "GMT+1:00 Europe/Andorra"
    case gmt100EuropeBerlin = "GMT+1:00 Europe/Berlin"
    case gmt100EuropeBrussels = "GMT+1:00 Europe/Brussels"
    case gmt100EuropeBudapest = "GMT+1:00 Europe/Budapest"
    case gmt100EuropeCopenhagen = "GMT+1:00 Europe/Copenhagen"
    case gmt100EuropeLuxembourg = "GMT+1:00 Europe/Luxembourg"
    case gmt100EuropeMadrid = "GMT+1:00 Europe/Madrid"
    case gmt100EuropeMonaco = "GMT+1:00 Europe/Monaco"
    case gmt100EuropeOslo = "GMT+1:00 Europe/Oslo"
    case gmt100EuropeParis = "GMT+1:00 Europe/Paris"
    case gmt100EuropePrague = "GMT+1:00 Europe/Prague"
    case gmt100EuropeStockholm = "GMT+1:00 Europe/Stockholm"
    case gmt100EuropeVienna = "GMT+1:00 Europe/Vienna"
    case gmt100EuropeWarsaw = "GMT+1:00 Europe/Warsaw"
    case gmt100EuropeZurich = "GMT+1:00 Europe/Zurich"
    case gmt1200PacificAuckland = "GMT+12:00 Pacific/Auckland"
    case gmt200AfricaCairo = "GMT+2:00 Africa/Cairo"
    case gmt200AsiaBeirut = "GMT+2:00 Asia/Beirut"
    case gmt200AsiaGaza = "GMT+2:00 Asia/Gaza"
    case gmt200AsiaIstanbul = "GMT+2:00 Asia/Istanbul"
    case gmt200AsiaJerusalem = "GMT+2:00 Asia/Jerusalem"
    case gmt200AsiaNicosia = "GMT+2:00 Asia/Nicosia"
    case gmt200EuropeAthens = "GMT+2:00 Europe/Athens"
    case gmt200EuropeBucharest = "GMT+2:00 Europe/Bucharest"
    case gmt200EuropeHelsinki = "GMT+2:00 Europe/Helsinki"
    case gmt200EuropeIstanbul = "GMT+2:00 Europe/Istanbul"
    case gmt200EuropeSofia = "GMT+2:00 Europe/Sofia"
    case gmt300EuropeMoscow = "GMT+3:00 Europe/Moscow"
    case gmt400AsiaBaku = "GMT+4:00 Asia/Baku"
    case gmt400EuropeSamara = "GMT+4:00 Europe/Samara"
    case gmt500AsiaYekaterinburg = "GMT+5:00 Asia/Yekaterinburg"
}

typealias StateLocations = [String: [Location]]
